apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: rev-proxy
  name: rev-proxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: rev-proxy
    spec:
      containers:
      - image: kdjordan/udagram-reverse-proxy
        name: rev-proxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


